name: Rust API Deploy Prod

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name for manual trigger'
        required: true
        default: "Manual Trigger"
  push:
    branches: [ main ]
    paths:
      - 'rust_todo_api/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'rust_todo_api/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: us-central1-docker.pkg.dev
  IMAGE_NAME: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}/rust.todo.api

jobs:
  # test:
  #   name: Test
  #   environment: Test
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       node-version: [20.x]
  #   defaults:
  #     run:
  #       working-directory: ./rust_todo_api

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: 'Create env file'
  #       run: |
  #         rm -rf .test.env
  #         touch .test.env
  #         echo MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} >> .test.env
  #         echo MYSQL_HOST=${{ secrets.MYSQL_HOST }} >> .test.env
  #         echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .test.env
  #         echo MYSQL_USER=${{ secrets.MYSQL_USER }} >> .test.env
  #         cat .test.env

  build:
    name: Build
    environment: Production
    # needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust_todo_api

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: "Authenticate Google Cloud"
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/731679007643/locations/global/workloadIdentityPools/github-actions/providers/rails-todo-identity-pool-github'
          service_account: github-actions@rails-todo-app-386721.iam.gserviceaccount.com

      - name: Configure Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet $REGISTRY

      - name: 'Create env file'
        run: |
          rm -rf .env
          touch .env
          echo DATABASE_URL=${{ secrets.RUST_MYSQL_DB_URL }} >> .env
          cat .env

      - name: Build Docker Image
        run: docker build -f ./Dockerfile -t $IMAGE_NAME .

      - name: Push Docker Image
        run: docker push $IMAGE_NAME

  deploy:
    name: Deploy
    environment: Production
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust_todo_api

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        name: "Authenticate Google Cloud"
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/731679007643/locations/global/workloadIdentityPools/github-actions/providers/rails-todo-identity-pool-github'
          service_account: github-actions@rails-todo-app-386721.iam.gserviceaccount.com

      - name: Configure Google Cloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy Docker Image
        run: gcloud run deploy rust-todo-api --image $IMAGE_NAME --region us-central1 --platform managed --port 5000